// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdviceController from "./advice_controller"
application.register("advice", AdviceController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapDirectionsController from "./map_directions_controller"
application.register("map-directions", MapDirectionsController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SweetAlertController from "./sweet_alert_controller"
application.register("sweet-alert", SweetAlertController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
